using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using VICCO.DAL;

namespace VICCO
{
    public partial class AutogeneratedSuperpo : System.Web.UI.Page
    {
        public void Getsuperstockalert()
        {
            try
            {
                Super_Auto_GenratePO objStock = new Super_Auto_GenratePO();
                objStock.SP_OPERATION = "INSERT";
                objStock.Getstock();

                objStock = new Super_Auto_GenratePO();
                objStock.IS_NOT_GENERATE = "TRUE";
                objStock.SP_OPERATION = "GET_FOR_PO";
                DataTable dt = new DataTable();
                dt = objStock.Getstock();              

                grdReport.DataSource = objStock.Getstock();
                grdReport.DataBind();

                if (dt.Rows.Count == 0)
                {
                    errorMsg.Visible = true;
                }
                else
                {
                    grdReport.HeaderRow.TableSection = TableRowSection.TableHeader;
                    grdReport.UseAccessibleHeader = true;
                    errorMsg.Visible = false;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }        
        protected void Page_Load(object sender, EventArgs e)
        {
            if(!IsPostBack)
            {
                Getsuperstockalert();
            }
        }

        //protected void btnClickGenratePO(object sender, EventArgs e)
        //{
        //    Super_Auto_GenratePO objStock = new Super_Auto_GenratePO();
        //    foreach (GridViewRow gvrow in grdReport.Rows)
        //    {
        //        var checkbox = gvrow.FindControl("CheckBox1") as CheckBox;
        //        string id = grdReport.DataKeys[gvrow.RowIndex].Value.ToString();

        //        objStock.ID = Convert.ToInt32(id);

        //        if (checkbox.Checked)
        //        {
        //            objStock.IS_NOT_GENERATE = "True";
        //        }
        //        else
        //        {
        //            objStock.IS_NOT_GENERATE = "False";
        //        }

        //        objStock.SP_OPERATION = "UPDATE";
        //        objStock.Getstock();
        //    }

        //    grdReport.DataSource = null;
        //    grdReport.DataBind();
        //    lblSuccess.Text = "PO Created Successfully and Sended to Mail...";
           
        //    stockdiv.Style.Add("height", "auto");

        //    objStock = new Super_Auto_GenratePO();
        //    objStock.SP_OPERATION = "GET_PO_STOCKIST";
        //    DataTable dt = new DataTable();
        //    dt = objStock.Getstock();

        //    for (int i = 0; i < dt.Rows.Count; i++)
        //    {

        //        objStock = new Super_Auto_GenratePO();
        //        objStock.STOCKIST_ID = Convert.ToInt32(dt.Rows[i]["STOCKIST_ID"]);
        //        objStock.SP_OPERATION = "SEND_PO";
        //        DataTable dtpo = new DataTable();
        //        dtpo = objStock.Getstock();

        //        NoInWord obj = new NoInWord();
        //        string amountinworld = obj.NumWordsWrapper(Convert.ToInt32(dtpo.Rows[0]["GRAND_TOTAL"]));
        //        dtpo.Columns.Add("TOTAL_IN_WORD", typeof(System.String));
        //        dtpo.Rows[0]["TOTAL_IN_WORD"] = amountinworld + " Rupees";

        //        objStock = new Super_Auto_GenratePO();
        //        objStock.SPURCHASEORDER_ID = Convert.ToInt32(dtpo.Rows[0]["SPURCHASEORDER_ID"]);
        //        objStock.SP_OPERATION = "GET_PO_PRODUCT";
        //        DataTable dtProduct = new DataTable();
        //        dtProduct = objStock.Getstock();

        //        ReportViewer1.LocalReport.ReportPath = Server.MapPath("~/AutoGenerateStockistPO.rdlc");
        //        ReportViewer1.LocalReport.DataSources.Clear();
        //        ReportDataSource _rsource1 = new ReportDataSource("DataSet1", dtpo);
        //        ReportViewer1.LocalReport.DataSources.Add(_rsource1);

        //        ReportDataSource _rsource2 = new ReportDataSource("DataSet2", dtProduct);
        //        ReportViewer1.LocalReport.DataSources.Add(_rsource2);

        //        ReportViewer1.LocalReport.Refresh();

        //        Warning[] warnings;
        //        string[] streamIds;
        //        string mimeType;
        //        string encoding = string.Empty;
        //        string extension = string.Empty;

        //        byte[] bytes = ReportViewer1.LocalReport.Render(
        //            "PDF",
        //            null,
        //            out mimeType,
        //            out encoding,
        //            out extension,
        //            out streamIds,
        //            out warnings);

        //        //Response.Buffer = true;
        //        //Response.Clear();
        //        //Response.ContentType = mimeType;

        //        //Response.AppendHeader("Content-Disposition", "inline; filename=vocco_invoice.xlsx");

        //        string filename = Convert.ToInt32(dt.Rows[i]["STOCKIST_ID"]) + "_" + System.DateTime.Now.ToString("ddMMyyyyhhmm.") + extension;

        //        using (var fs = new System.IO.FileStream(Server.MapPath("~/AutoGenratedPO/" + filename), System.IO.FileMode.Create))
        //        {
        //            fs.Write(bytes, 0, bytes.Length);
        //            fs.Close();
        //        }

        //        SendEmail("manjusha@viccolabs.com ", filename);

        //        objStock = new Super_Auto_GenratePO();
        //        objStock.STOCKIST_ID = Convert.ToInt32(dt.Rows[i]["STOCKIST_ID"]);
        //        objStock.SP_OPERATION = "UPDATE_FOR_MAIL_SENDED";
        //        objStock.Getstock();
        //    }
       // }
    }
}