using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using VICCO.DAL;
using System.Data;
using Microsoft.Reporting.WebForms;
using YOGESH_INVOICE.DAL;

namespace VICCO
{
    public partial class AutogeneratedPrint : System.Web.UI.Page
    {

        public void Getpo()
        {
            Super_Auto_GenratePO objStock = new Super_Auto_GenratePO();
            objStock.SPURCHASEORDER_ID = Convert.ToInt32(Request.QueryString["pono"]);
            objStock.SP_OPERATION = "GET_PO";
            DataTable dtpo = new DataTable();
            dtpo = objStock.Getstock();

            NoInWord obj = new NoInWord();
            string amountinworld = obj.NumWordsWrapper(Convert.ToInt32(dtpo.Rows[0]["GRAND_TOTAL"]));
            dtpo.Columns.Add("TOTAL_IN_WORD", typeof(System.String));
            dtpo.Rows[0]["TOTAL_IN_WORD"] = amountinworld + " Rupees";

            objStock = new Super_Auto_GenratePO();
            objStock.SPURCHASEORDER_ID = Convert.ToInt32(dtpo.Rows[0]["SPURCHASEORDER_ID"]);
            objStock.SP_OPERATION = "GET_PO_PRODUCT";
            DataTable dtProduct = new DataTable();
            dtProduct = objStock.Getstock();

            ReportViewer1.LocalReport.ReportPath = Server.MapPath("~/AutoGenerateStockistPO.rdlc");
            ReportViewer1.LocalReport.DataSources.Clear();
            ReportDataSource _rsource1 = new ReportDataSource("DataSet1", dtpo);
            ReportViewer1.LocalReport.DataSources.Add(_rsource1);

            ReportDataSource _rsource2 = new ReportDataSource("DataSet2", dtProduct);
            ReportViewer1.LocalReport.DataSources.Add(_rsource2);

            ReportViewer1.LocalReport.Refresh();
           
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                Getpo();
            }

            Warning[] warnings;
            string[] streamIds;
            string mimeType = "application/pdf";
            string encoding = string.Empty;
            string extension = string.Empty;

            byte[] bytes = ReportViewer1.LocalReport.Render(
                "PDF",
                null,
                out mimeType,
                out encoding,
                out extension,
                out streamIds,
                out warnings);

            Response.Buffer = true;
            Response.Clear();
            Response.ContentType = mimeType;

            Response.AppendHeader("Content-Disposition", "inline; filename=AutoGenerated_PO.pdf");
            Response.OutputStream.Write(bytes, 0, bytes.Length);
            Response.Flush();
            Response.End();
        }
    }
}