<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Autogenerateditemview.aspx.cs" Inherits="VICCO.Autogenerateditemview" %>

<%@ Register Assembly="Microsoft.ReportViewer.WebForms, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" Namespace="Microsoft.Reporting.WebForms" TagPrefix="rsweb" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="mainpanel">
        <div class="contentpanel">
            <ol class="breadcrumb breadcrumb-quirk">
                <li><a href="Home.aspx"><i class="fa fa-home mr5"></i>Home</a></li>
                <li><a href="Autogenerateditemview.aspx">Super PO Items</a></li>
            </ol>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-danger">
                        <div class="panel-heading">
                            <h4 class="panel-title">Super PO Items</h4>
                        </div>
                        <div class="panel-body">

                            <div class="clearfix">
                            </div>
                            <div class="size">
                                <div class="table-responsive">
                                    <div id="errorMsg" runat="server" visible="false" class="alert alert-warning" style="background-color: #d8dce3; color: #505b72;">
                                        <strong>No record found..</strong>
                                    </div>
                                    <h4 class="text-center" style="line-height: 25px;">Generate PO For
                                        <br />
                                        <asp:Label ID="lblSupperName" CssClass="text-info" runat="server"></asp:Label><br />

                                    </h4>
                                    <h5 class="text-center">
                                        <asp:Label ID="lblMaterialCount" runat="server"></asp:Label></h5>
                                    <br />
                                    <h4 class="text-center">
                                        <asp:Label ID="lblSuccess" CssClass="text-success" runat="server"></asp:Label></h4>
                                    <asp:GridView ID="grdReport" runat="server" Width="100%" AutoGenerateColumns="False"
                                        BorderStyle="None" CssClass="table nomargin table-primary grid stock" DataKeyNames="ID">
                                        <AlternatingRowStyle BackColor="White" />
                                        <Columns>
                                            <asp:TemplateField HeaderText="SRNO" ItemStyle-HorizontalAlign="Left" >
                                                <ItemTemplate>
                                                    <asp:Label ID="Label1" runat="server" Font-Bold="false" Text='<%#Container.DataItemIndex+1 %>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField ItemStyle-HorizontalAlign="left" HeaderText="Material Name" >
                                                <ItemTemplate>
                                                    <asp:Label ID="Label2" runat="server" Font-Bold="false" Text='<%# Eval("MATERIAL_NAME")%>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                           <asp:TemplateField HeaderText="CURRENT STOCK" ItemStyle-Width="10%">
                                                <ItemTemplate>
                                                    <asp:Label ID="lblCurrentStock" runat="server" Text='<%# Eval("CURRENT_STOCK")%>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField HeaderText="MIN QTY REQUIRED (CS)" ItemStyle-Width="10%">
                                                <ItemTemplate>
                                                    <asp:Label ID="lblMinpoQty" runat="server" Text='<%# Eval("MIN_STOCK_CS")%>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField HeaderText="DIFFRENCE" ItemStyle-Width="10%">
                                                <ItemTemplate>
                                                    <asp:Label ID="lblDiffStock" runat="server" Text='<%# Eval("DIFF_STOCK")%>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField ItemStyle-HorizontalAlign="left"  HeaderText="PO QTY (CS)" >
                                                <ItemTemplate>                                                   
                                                    <asp:Label ID="Label6" runat="server" Font-Bold="false" Text='<%# Eval("DIFF_STOCK")%>'></asp:Label>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                            <asp:TemplateField ItemStyle-HorizontalAlign="Center" ItemStyle-Width="40px">
                                                <ItemTemplate>
                                                    <asp:LinkButton ID="btnRemove" runat="server" ForeColor="#FF5722" OnClick="RemoveProduct" CausesValidation="false">x</asp:LinkButton>
                                                </ItemTemplate>
                                            </asp:TemplateField>
                                        </Columns>
                                        <PagerStyle CssClass="pagination" />
                                    </asp:GridView>
                                    <rsweb:ReportViewer ID="ReportViewer1" runat="server" Visible="false"></rsweb:ReportViewer>
                                    <br />
                                    <asp:Button ID="Button1" runat="server" Text="Generate PO" OnClick="btnSubmit_Click" CssClass="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
